###############################
# Makefile for dynamic string #
# Author: Vojtěch Ulej        #
###############################

# Compiler
CC = gcc
CFLAGS =-std=c11 -Wall -Wextra -g

SRC=symtable-test.c ../../symtable.c

.PHONY: all
all: $(SRC)
	$(CC) $(CFLAGS) $(SRC) -o symtable_test

